# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-21 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('average_cost', models.IntegerField()),
                ('location', models.CharField(max_length=70)),
                ('website', models.CharField(max_length=1000)),
            ],
        ),
    ]
